(ns seon.db.schema
  "Malli schemas for financial domain entities.

  Defines schemas for:
  - Options quotes (matching OPRA feed structure)
  - Greeks (Delta, Gamma, Vega, Theta)
  - Implied Volatility Surface
  - Trading signals and strategies

  Includes custom generators for property-based testing."
  (:require [malli.core :as m]
            [malli.generator :as mg]
            [malli.registry :as mr]
            [malli.util :as mu]
            [tick.core :as t]))

;;; ---------------------------------------------------------------------------
;;; Custom Generators
;;; ---------------------------------------------------------------------------

(def gen-ticker
  "Generator for stock ticker symbols."
  [:string {:min 1 :max 5
            :gen/elements ["AAPL" "MSFT" "GOOGL" "AMZN" "META"
                           "NVDA" "TSLA" "SPY" "QQQ" "IWM"]}])

(def gen-strike
  "Generator for strike prices (positive, reasonable range)."
  [:double {:min 1.0 :max 10000.0}])

(def gen-price
  "Generator for option prices (non-negative)."
  [:double {:min 0.0 :max 1000.0}])

(def gen-iv
  "Generator for implied volatility (0-500% range)."
  [:double {:min 0.01 :max 5.0}])

(def gen-delta
  "Generator for delta (-1 to 1)."
  [:double {:min -1.0 :max 1.0}])

(def gen-gamma
  "Generator for gamma (non-negative)."
  [:double {:min 0.0 :max 1.0}])

(def gen-vega
  "Generator for vega (non-negative)."
  [:double {:min 0.0 :max 100.0}])

(def gen-theta
  "Generator for theta (typically negative for long options)."
  [:double {:min -10.0 :max 0.0}])

;;; ---------------------------------------------------------------------------
;;; Core Schemas
;;; ---------------------------------------------------------------------------

(def OptionType
  "Option type: call or put."
  [:enum :call :put])

(def AggressorSide
  "Trade aggressor side."
  [:enum :buy :sell])

(def OptionQuote
  "Schema for an options quote (Table 1 from the paper).

  Maps directly to OPRA feed structure with calculated Greeks.

  ID format: \"{OCC_SYMBOL}-{ISO_TIMESTAMP}\" for deterministic deduplication.
  Example: \"AAPL231215C00185000-2024-11-01T14:00:00Z\""
  [:map {:closed true}
   [:xt/id :string]  ; Deterministic ID for deduplication (OCC symbol + timestamp)
   [:asset/ticker gen-ticker]
   [:option/id :string]  ; OCC symbol e.g., \"AAPL230616C00150000\"
   [:option/strike gen-strike]
   [:option/type OptionType]
   [:option/expiry inst?]
   [:quote/bid gen-price]
   [:quote/ask gen-price]
   [:quote/iv {:optional true} gen-iv]
   [:greeks/delta {:optional true} gen-delta]
   [:greeks/gamma {:optional true} gen-gamma]
   [:greeks/vega {:optional true} gen-vega]
   [:greeks/theta {:optional true} gen-theta]
   [:market/volume {:optional true} :int]
   [:market/aggressor {:optional true} AggressorSide]])

(def Greeks
  "Schema for option Greeks."
  [:map
   [:delta gen-delta]
   [:gamma gen-gamma]
   [:vega gen-vega]
   [:theta gen-theta]
   [:vanna {:optional true} :double]
   [:charm {:optional true} :double]
   [:volga {:optional true} :double]])

(def IVSurfacePoint
  "A single point on the implied volatility surface."
  [:map
   [:strike gen-strike]
   [:expiry inst?]
   [:iv gen-iv]
   [:delta {:optional true} gen-delta]])

(def IVSurface
  "Implied volatility surface for a single underlying.

  ID format: \"{TICKER}-surface-{ISO_TIMESTAMP}\" for deterministic deduplication."
  [:map
   [:xt/id :string]  ; Deterministic ID
   [:asset/ticker gen-ticker]
   [:surface/timestamp inst?]
   [:surface/points [:vector IVSurfacePoint]]
   ;; SVI parameterization (optional)
   [:svi/a {:optional true} :double]
   [:svi/b {:optional true} :double]
   [:svi/rho {:optional true} :double]
   [:svi/m {:optional true} :double]
   [:svi/sigma {:optional true} :double]])

(def TradingSignal
  "A trading signal generated by the DSL."
  [:map
   [:signal/id :uuid]
   [:signal/timestamp inst?]
   [:signal/ticker gen-ticker]
   [:signal/action [:enum :buy :sell :hold]]
   [:signal/strategy [:enum :long-straddle :short-straddle
                      :gamma-scalp :dispersion
                      :vol-arb :iron-condor]]
   [:signal/confidence [:double {:min 0.0 :max 1.0}]]
   [:signal/reasoning {:optional true} :string]])

;;; ---------------------------------------------------------------------------
;;; Registry
;;; ---------------------------------------------------------------------------

(def registry
  "Malli schema registry for the trading domain."
  (atom
   (merge
    (m/default-schemas)
    {:option/type OptionType
     :option/quote OptionQuote
     :option/greeks Greeks
     :iv/surface-point IVSurfacePoint
     :iv/surface IVSurface
     :trading/signal TradingSignal
     :aggressor/side AggressorSide})))

(defn validate
  "Validate data against a schema.

  Args:
    schema - Schema keyword or inline schema
    data - Data to validate

  Returns:
    true if valid, false otherwise"
  [schema data]
  (m/validate schema data {:registry @registry}))

(defn explain
  "Explain validation errors.

  Args:
    schema - Schema keyword or inline schema
    data - Data to validate

  Returns:
    Explanation map or nil if valid"
  [schema data]
  (m/explain schema data {:registry @registry}))

(defn generate
  "Generate sample data from a schema.

  Args:
    schema - Schema keyword or inline schema
    opts - Generation options (:seed, :size)

  Returns:
    Generated sample data"
  ([schema]
   (generate schema {}))
  ([schema opts]
   (mg/generate schema (merge {:registry @registry} opts))))

(defn sample
  "Generate multiple samples from a schema.

  Args:
    schema - Schema keyword or inline schema
    n - Number of samples (default 10)

  Returns:
    Sequence of generated samples"
  ([schema]
   (sample schema 10))
  ([schema n]
   (mg/sample schema {:registry @registry :size n})))
