(ns seon.schema
  "Global Malli schema registry for Seon.

   Provides a centralized, mutable registry for domain schemas. All namespaces
   register their schemas here using `register!`, making them available for:
   - Function schema validation via `m/=>` or `:malli/schema` metadata
   - Generative testing via `malli.generator`
   - Runtime validation via `malli.core/validate`

   Usage:
     (require '[seon.schema :as schema])

     ;; Register schemas using auto-namespaced keywords
     (schema/register! ::user-id :uuid)
     (schema/register! ::user-name [:string {:min 1 :max 200}])

     ;; Or register multiple at once
     (schema/register-all!
       ::order-id :uuid
       ::order-total [:double {:min 0}])

   The `::` syntax expands to the current namespace, so `::user-id` in
   `seon.trading.core` becomes `:seon.trading.core/user-id`.

   This design makes it easy for LLM agents to:
   - Parse individual `register!` forms
   - Update single schema definitions
   - Track which schemas are defined in which namespace"
  (:require [malli.core :as m]
            [malli.registry :as mr]))

;;; ---------------------------------------------------------------------------
;;; Registry Setup
;;; ---------------------------------------------------------------------------

;; Atom holding all registered domain schemas.
;; Use `defonce` to survive namespace reloads.
(defonce ^:private *schemas (atom {}))

;; Initialize the global registry once at load time.
;; Combines Malli's default schemas with our mutable registry.
(defonce ^:private _registry-init
  (mr/set-default-registry!
   (mr/composite-registry
    (m/default-schemas)
    (mr/mutable-registry *schemas))))

;; Register :inst as a keyword type (Malli only provides inst? predicate).
;; This lets schemas use :inst instead of inst? for consistency with :string, :int, etc.
(defonce ^:private _inst-type
  (swap! *schemas assoc :inst (m/-simple-schema {:type :inst :pred inst?})))

;; Register :seon.flow/dynamic — a wire protocol field validated dynamically.
;; Used for ::args, ::value, and ::payload in flow message envelopes.
;; These fields carry data whose type depends on the target function or
;; payload key, so static schema can only assert non-nil. Real validation
;; happens at the message boundary via validate-fn-args!, validate-fn-value!,
;; and validate-payload! in seon.flow.msg.
(defonce ^:private _dynamic-type
  (swap! *schemas assoc :seon.flow/dynamic
         (m/-simple-schema
          {:type :seon.flow/dynamic
           :pred some?
           :type-properties {:gen/schema [:or :int :string :keyword :boolean
                                          [:vector :int] [:map-of :keyword :string]]
                             :gen/fmap identity}})))

;; Register :seon.db/namespace — the entity-namespace stamp attached by
;; `seon.db/transact!` when routing through the datahike flow (Decision 7 of
;; the datahike-migration PRD). Values are db-name keywords (:seon.weather,
;; :seon.phase2.demo, etc). Registered here so the validation gate in
;; seon.db/transact! treats it as a known attr without domain code needing
;; to register it explicitly.
(defonce ^:private _db-namespace-type
  (swap! *schemas assoc :seon.db/namespace :keyword))

;; Register :seon.db/lookup-ref-value — the value position in a lookup-ref.
;; Datahike accepts strings, uuids, keywords, and ints as unique-attr values.
(defonce ^:private _lookup-ref-value-type
  (swap! *schemas assoc :seon.db/lookup-ref-value
         [:or :string :uuid :keyword :int]))

;; Register :seon.db/ref — an intra-DB :db.type/ref.
;; At transact time, datahike resolves any of the supported forms to an eid:
;;   - pos-int  : an existing entity-id
;;   - neg-int  : a numeric tempid
;;   - string   : a string tempid
;;   - [k v]    : a lookup-ref against unique attribute k with value v
;; Cross-DB handles are :uuid attrs with :seon.db/ref-to metadata; they are
;; NEVER labeled :seon.db/ref.
;; Reference: docs/prds/datahike-migration/ref-model-research.md.
(defonce ^:private _ref-type
  (swap! *schemas assoc :seon.db/ref
         [:or
          :int
          :string
          [:tuple :keyword :seon.db/lookup-ref-value]]))

;; Register :seon.db/id — the canonical id-string shape used by every
;; entity identity attr and every tx-meta scalar id. Locked 2026-05-23
;; to <3-letter-random>-<YYMMDDHHmm> (14 chars; generated by
;; seon.db/new-id!). Single source of truth: bump this and every
;; identity-attr length constraint updates.
;;
;; Reference patterns (per CLAUDE.md "Shared schema shapes"):
;;   - Bare-keyword reference for plain scalars:
;;       (schema/register! :seon.db/agent-id :seon.db/id)
;;   - :and wrap for identity attrs (adds {:seon.db/identity true}):
;;       (schema/register! :seon.agent/id [:and {:seon.db/identity true} :seon.db/id])
;;
;; Bridge handles both shapes today; see seon.db/malli->datahike-attr.
(defonce ^:private _id-type
  (swap! *schemas assoc :seon.db/id [:string {:min 14 :max 14}]))

;;; ---------------------------------------------------------------------------
;;; Registration API
;;; ---------------------------------------------------------------------------

(defn register!
  "Register a single schema in the global registry.

   Arguments:
     k - Schema keyword (use `::name` for auto-namespacing)
     v - Malli schema definition

   Returns:
     The registered schema keyword.

   Example:
     (register! ::api-key [:string {:min 1}])
     (register! ::timeout [:int {:min 1000 :max 600000}])"
  [k v]
  (swap! *schemas assoc k v)
  k)

(defn current-keys
  "Snapshot of all currently-registered schema keywords. Used by
   detect-and-tee in eval-batch! for atom-diff schema detection
   (compare before vs after an eval to see what the form registered)."
  []
  (set (keys @*schemas)))

(defn register-all!
  "Register multiple schemas at once.

   Arguments:
     Pairs of keyword and schema definition.

   Returns:
     Set of registered schema keywords.

   Throws:
     AssertionError if odd number of arguments provided.

   Example:
     (register-all!
       ::user-id :uuid
       ::user-name [:string {:min 1}]
       ::user-email [:string {:min 5}])"
  [& kvs]
  (assert (even? (count kvs)) "register-all! requires pairs of [key schema]")
  (let [pairs (partition 2 kvs)]
    (doseq [[k v] pairs]
      (register! k v))
    (set (map first pairs))))

;;; ---------------------------------------------------------------------------
;;; Introspection
;;; ---------------------------------------------------------------------------

(defn registered-schemas
  "Return a map of all registered domain schemas.

   Does not include Malli's built-in schemas."
  []
  @*schemas)

(defn registered?
  "Check if a schema keyword is registered."
  [k]
  (contains? @*schemas k))

(defn schema-definition
  "Get the raw definition for a registered schema.

   Returns nil if not registered."
  [k]
  (get @*schemas k))

(defn schemas-in-namespace
  "Get all schemas registered under a specific namespace.

   Arguments:
     ns-name - String namespace name (e.g., \"seon.ai.gemini\")

   Returns:
     Map of {keyword definition} for schemas in that namespace."
  [ns-name]
  (into {}
        (filter (fn [[k _]]
                  (= (namespace k) ns-name))
                @*schemas)))

;;; ---------------------------------------------------------------------------
;;; Development Helpers
;;; ---------------------------------------------------------------------------

(defn clear-all!
  "Clear all registered schemas. USE WITH CAUTION - only for testing."
  []
  (reset! *schemas {}))

(comment
  ;; REPL exploration

  ;; Register a test schema
  (register! ::test-schema [:string {:min 1}])

  ;; Check what's registered
  (registered-schemas)
  (registered? ::test-schema)

  ;; Get schemas for a namespace
  (schemas-in-namespace "seon.schema")

  ;; Validate data against registered schema
  (m/validate ::test-schema "hello")
  (m/validate ::test-schema "")  ; fails - min 1

  ;; Generate sample data
  (require '[malli.generator :as mg])
  (mg/generate ::test-schema)

  nil)
