(ns seon.ai.datalevin
  "Parallel Datalevin storage for AI sessions and messages.

   This namespace provides Datalevin-backed storage that runs IN PARALLEL
   with the existing XTDB storage. It does NOT replace XTDB - both databases
   receive writes, but only XTDB is used for reads.

   ## Purpose

   Stress test Datalevin before committing to a full migration. The project
   owner experienced crashes with XTDB's compactor, so we need to verify
   Datalevin's stability under real load before migrating.

   ## Configuration

   Enable/disable via dynamic var (can be toggled at runtime):

   ```clojure
   ;; Enable parallel writes (default: true when Datalevin is available)
   (reset! seon.ai.datalevin/enabled? true)

   ;; Disable parallel writes
   (reset! seon.ai.datalevin/enabled? false)
   ```

   ## Schema Design

   Uses Datalevin's schemaless mode initially. Entities use the same
   namespaced keys as XTDB entities but with Datalevin-compatible structure:

   - `:db/id` instead of `:xt/id` (Datalevin's entity ID)
   - `:seon.ai/session-id` stored as a unique indexed attribute
   - Timestamps stored as instants (Datalevin supports java.time.Instant)

   ## What Gets Stored

   - AI Sessions: same data as XTDB ai_sessions table
   - AI Messages: same data as XTDB ai_messages table

   ## Monitoring

   - All writes are logged at :debug level
   - Errors are logged at :warn level but don't fail the main operation
   - Use `(stats)` to get storage statistics"
  (:require [integrant.repl.state :as state]
            [seon.ai :as ai]
            [seon.db.datalevin.conn :as conn]
            [seon.schema :as schema]
            [taoensso.timbre :as log])
  (:import [java.time Instant]
           [java.util UUID]))

;;; ---------------------------------------------------------------------------
;;; Configuration
;;; ---------------------------------------------------------------------------

;; Atom controlling whether Datalevin writes are enabled.
;; Set to false to disable parallel writes (e.g., if Datalevin is unstable).
(defonce enabled? (atom true))

(defn set-enabled!
  "Enable or disable Datalevin parallel writes.

   Usage:
     (set-enabled! true)   ; Enable parallel writes
     (set-enabled! false)  ; Disable parallel writes

   Returns the new state."
  [value]
  (reset! enabled? (boolean value)))

;;; ---------------------------------------------------------------------------
;;; Schema Registration
;;; ---------------------------------------------------------------------------

(schema/register! ::write-count
                  [:int {:min 0 :description "Number of successful writes"}])

(schema/register! ::error-count
                  [:int {:min 0 :description "Number of failed writes"}])

(schema/register! ::last-write-at
                  [:any {:description "Timestamp of last successful write"}])

(schema/register! ::session-count
                  [:int {:min 0 :description "Number of sessions stored"}])

(schema/register! ::message-count
                  [:int {:min 0 :description "Number of messages stored"}])

;;; ---------------------------------------------------------------------------
;;; Statistics
;;; ---------------------------------------------------------------------------

;; Atom tracking write statistics for monitoring.
(defonce stats-atom
  (atom {:write-count 0
         :error-count 0
         :last-write-at nil
         :session-writes 0
         :message-writes 0}))

(defn stats
  "Get current Datalevin storage statistics.

   Returns:
     Map with :write-count, :error-count, :last-write-at, etc."
  []
  @stats-atom)

(defn reset-stats!
  "Reset statistics counters."
  []
  (reset! stats-atom {:write-count 0
                      :error-count 0
                      :last-write-at nil
                      :session-writes 0
                      :message-writes 0}))

;;; ---------------------------------------------------------------------------
;;; Connection Helpers
;;; ---------------------------------------------------------------------------

(defn- get-conn
  "Get Datalevin master connection from Integrant system.
   Returns nil if system not running or connection unavailable."
  []
  (when-let [mgr (:seon/connection-manager state/system)]
    (try
      (conn/get-master-conn! {::conn/manager mgr})
      (catch Exception e
        (log/warn "Failed to get Datalevin connection" {:error (.getMessage e)})
        nil))))

;;; ---------------------------------------------------------------------------
;;; Entity Conversion
;;; ---------------------------------------------------------------------------

(defn- xtdb->datalevin-session
  "Convert XTDB session entity to Datalevin format.

   Key differences:
   - :xt/id -> stored separately as :seon.ai/xtdb-id for traceability
   - :db/id is auto-generated by Datalevin
   - All other fields pass through unchanged"
  [entity]
  (let [session-id (:xt/id entity)]
    (-> entity
        (dissoc :xt/id)
        (assoc :seon.ai.datalevin/xtdb-id session-id
               :seon.ai.datalevin/entity-type :session
               :seon.ai.datalevin/stored-at (Instant/now)))))

(defn- xtdb->datalevin-message
  "Convert XTDB message entity to Datalevin format."
  [entity]
  (let [message-id (:xt/id entity)]
    (-> entity
        (dissoc :xt/id)
        (assoc :seon.ai.datalevin/xtdb-id message-id
               :seon.ai.datalevin/entity-type :message
               :seon.ai.datalevin/stored-at (Instant/now)))))

;;; ---------------------------------------------------------------------------
;;; Write Operations (Parallel to XTDB)
;;; ---------------------------------------------------------------------------

(defn save-session!
  "Save a session entity to Datalevin (parallel to XTDB write).

   Called by seon.ai after successful XTDB write. This is fire-and-forget:
   errors are logged but don't propagate to caller.

   Args:
     entity - Session entity map (with :xt/id)

   Returns:
     true if write succeeded, false if failed or disabled"
  [entity]
  (if-not @enabled?
    (do (log/trace "Datalevin writes disabled, skipping session")
        false)
    (try
      (when-let [conn (get-conn)]
        (require 'datalevin.core)
        (let [transact! (resolve 'datalevin.core/transact!)
              dl-entity (xtdb->datalevin-session entity)]
          (transact! conn [dl-entity])
          (swap! stats-atom (fn [s]
                              (-> s
                                  (update :write-count inc)
                                  (update :session-writes inc)
                                  (assoc :last-write-at (Instant/now)))))
          (log/debug "Saved session to Datalevin"
                     {:session-id (::ai/session-id entity)
                      :xtdb-id (:xt/id entity)})
          true))
      (catch Exception e
        (swap! stats-atom update :error-count inc)
        (log/warn "Failed to save session to Datalevin"
                  {:session-id (::ai/session-id entity)
                   :error (.getMessage e)})
        false))))

(defn save-message!
  "Save a message entity to Datalevin (parallel to XTDB write).

   Called by seon.ai.claude after successful XTDB write. Fire-and-forget.

   Args:
     entity - Message entity map (with :xt/id)

   Returns:
     true if write succeeded, false if failed or disabled"
  [entity]
  (if-not @enabled?
    (do (log/trace "Datalevin writes disabled, skipping message")
        false)
    (try
      (when-let [conn (get-conn)]
        (require 'datalevin.core)
        (let [transact! (resolve 'datalevin.core/transact!)
              dl-entity (xtdb->datalevin-message entity)]
          (transact! conn [dl-entity])
          (swap! stats-atom (fn [s]
                              (-> s
                                  (update :write-count inc)
                                  (update :message-writes inc)
                                  (assoc :last-write-at (Instant/now)))))
          (log/trace "Saved message to Datalevin"
                     {:message-id (:xt/id entity)
                      :session-id (::ai/session-id entity)})
          true))
      (catch Exception e
        (swap! stats-atom update :error-count inc)
        (log/warn "Failed to save message to Datalevin"
                  {:message-id (:xt/id entity)
                   :error (.getMessage e)})
        false))))

(defn update-session!
  "Update a session entity in Datalevin (for end-session).

   Finds existing session by xtdb-id and updates it with new fields.

   Args:
     entity - Updated session entity map (with :xt/id)

   Returns:
     true if write succeeded, false if failed or disabled"
  [entity]
  (if-not @enabled?
    false
    (try
      (when-let [conn (get-conn)]
        (require 'datalevin.core)
        (let [q-fn (resolve 'datalevin.core/q)
              transact! (resolve 'datalevin.core/transact!)
              xtdb-id (:xt/id entity)
              ;; Find existing entity by xtdb-id
              existing (first (q-fn '[:find ?e
                                      :in $ ?xtdb-id
                                      :where
                                      [?e :seon.ai.datalevin/xtdb-id ?xtdb-id]]
                                    @conn xtdb-id))]
          (if existing
            ;; Update existing entity
            (let [db-id (first existing)
                  dl-entity (-> (xtdb->datalevin-session entity)
                                (assoc :db/id db-id))]
              (transact! conn [dl-entity])
              (swap! stats-atom (fn [s]
                                  (-> s
                                      (update :write-count inc)
                                      (assoc :last-write-at (Instant/now)))))
              (log/debug "Updated session in Datalevin" {:xtdb-id xtdb-id})
              true)
            ;; No existing entity - insert new one
            (save-session! entity))))
      (catch Exception e
        (swap! stats-atom update :error-count inc)
        (log/warn "Failed to update session in Datalevin"
                  {:session-id (:xt/id entity)
                   :error (.getMessage e)})
        false))))

;;; ---------------------------------------------------------------------------
;;; Query Operations (For Verification)
;;; ---------------------------------------------------------------------------

(defn query-sessions
  "Query sessions from Datalevin for verification.

   Opts:
     :limit - Max results (default 20)
     :status - Filter by status

   Returns:
     Vector of session entities"
  ([] (query-sessions {}))
  ([opts]
   (when-let [conn (get-conn)]
     (require 'datalevin.core)
     (let [q-fn (resolve 'datalevin.core/q)
           pull (resolve 'datalevin.core/pull)
           limit (or (:limit opts) 20)
           results (q-fn '[:find ?e ?stored
                           :in $
                           :where
                           [?e :seon.ai.datalevin/entity-type :session]
                           [?e :seon.ai.datalevin/stored-at ?stored]]
                         @conn)]
       (->> results
            (sort-by second #(compare %2 %1))  ; Most recent first
            (take limit)
            (mapv (fn [[eid _]]
                    (pull @conn '[*] eid))))))))

(defn query-messages
  "Query messages from Datalevin for verification.

   Opts:
     :session-id - Filter by AI session ID
     :limit - Max results (default 100)

   Returns:
     Vector of message entities"
  ([] (query-messages {}))
  ([opts]
   (when-let [conn (get-conn)]
     (require 'datalevin.core)
     (let [q-fn (resolve 'datalevin.core/q)
           pull (resolve 'datalevin.core/pull)
           limit (or (:limit opts) 100)
           session-id (:session-id opts)
           results (if session-id
                     ;; Filter by session-id
                     (q-fn '[:find ?e ?stored
                             :in $ ?sid
                             :where
                             [?e :seon.ai.datalevin/entity-type :message]
                             [?e :seon.ai/session-id ?sid]
                             [?e :seon.ai.datalevin/stored-at ?stored]]
                           @conn session-id)
                     ;; All messages
                     (q-fn '[:find ?e ?stored
                             :where
                             [?e :seon.ai.datalevin/entity-type :message]
                             [?e :seon.ai.datalevin/stored-at ?stored]]
                           @conn))]
       (->> results
            (sort-by second #(compare %2 %1))
            (take limit)
            (mapv (fn [[eid _]]
                    (pull @conn '[*] eid))))))))

(defn count-entities
  "Count entities in Datalevin by type.

   Returns:
     Map with :sessions and :messages counts"
  []
  (when-let [conn (get-conn)]
    (require 'datalevin.core)
    (let [q-fn (resolve 'datalevin.core/q)
          session-count (count (q-fn '[:find ?e
                                       :where
                                       [?e :seon.ai.datalevin/entity-type :session]]
                                     @conn))
          message-count (count (q-fn '[:find ?e
                                       :where
                                       [?e :seon.ai.datalevin/entity-type :message]]
                                     @conn))]
      {:sessions session-count
       :messages message-count})))

;;; ---------------------------------------------------------------------------
;;; Verification (Compare with XTDB)
;;; ---------------------------------------------------------------------------

(defn verify-sync
  "Compare Datalevin counts with XTDB counts.

   Returns:
     Map with :datalevin, :xtdb, and :in-sync? keys"
  []
  (let [dl-counts (count-entities)
        node (:seon/xtdb-node state/system)
        xtdb-sessions (when node
                        (require 'seon.db.node)
                        (let [q-fn (resolve 'seon.db.node/q)]
                          (count (q-fn node "SELECT _id FROM ai_sessions"))))
        xtdb-messages (when node
                        (require 'seon.db.node)
                        (let [q-fn (resolve 'seon.db.node/q)]
                          (count (q-fn node "SELECT _id FROM ai_messages"))))]
    {:datalevin dl-counts
     :xtdb {:sessions xtdb-sessions
            :messages xtdb-messages}
     :in-sync? (and (= (:sessions dl-counts) xtdb-sessions)
                    (= (:messages dl-counts) xtdb-messages))}))

;;; ---------------------------------------------------------------------------
;;; REPL Helpers
;;; ---------------------------------------------------------------------------

(comment
  ;; Check if enabled
  @enabled?

  ;; Toggle
  (set-enabled! true)
  (set-enabled! false)

  ;; View stats
  (stats)

  ;; Reset stats
  (reset-stats!)

  ;; Count entities
  (count-entities)

  ;; Query sessions
  (query-sessions {:limit 5})

  ;; Query messages
  (query-messages {:limit 10})

  ;; Verify sync with XTDB
  (verify-sync)

  nil)
