(ns seon.issue.detect
  "Detectors: one database value in, the subjects that fail one standard out.

  A detector is an ordinary read. It returns a vector of subject maps, each
  carrying exactly ONE installed identity attribute and its value — never a
  bare entity id, which a refork would change — plus the prose the generator
  writes once (`:seon.issue/title`, `:seon.issue/problem`) and the namespaces
  responsible for the finding. `seon.issue/generate` turns those subjects into
  issue entities whose identity is the detector plus the subject identity, so
  running a detector twice upserts the same entities."
  (:require [malli.registry :as mr]
            [seon.schema.internal :as internal]
            [seon.db :as db]
            [seon.fn :as fn]))

(defn- declared-keys
  "The attribute keys one entity-map schema declares, from its stored shape."
  [database entity]
  (let [key (:seon.schema/key (db/pull database '[:seon.schema/key] entity))
        registry (:seon.schema.projection/registry (db/carried-projection database))]
    (into #{} (map first) (internal/entity-entries (mr/schema registry key)))))

(defn- component-values
  "Every entity that is the value of an attribute declared `:seon.db/component`."
  [database]
  (into #{}
        (mapcat (fn [attribute] (map :v (db/datoms database :aevt attribute))))
        (db/q '[:find [?key ...] :where
                [?e :seon.schema/key ?key] [?e :seon.db/component true]]
              database)))

(defn- instances
  "Entities whose whole attribute set lies inside one entity map's declared keys.
  An entity IS its attributes: no kind stamp decides this, and an entity holding
  an attribute the map does not declare is another entity sharing a key."
  [database entity-keys]
  (->> (into #{}
             (mapcat (fn [attribute] (map :e (db/datoms database :aevt attribute))))
             entity-keys)
       (filter (fn [entity]
                 (every? #(contains? entity-keys (:a %)) (db/datoms database :eavt entity))))))

(defn- pair-subject [database components namespaces [schema-key entity]]
  (let [entity-keys (declared-keys database entity)]
    (when-not (some components (instances database entity-keys))
      (cond-> {:seon.schema/key schema-key
               :seon.issue/title (str "Entity map " schema-key " declares no render pair")
               :seon.issue/problem
               (str "The entity map " schema-key " is stored (:seon.db/attributes true) and declares neither "
                    ":seon.render/ai nor :seon.render/html, so its entities reach an agent and the web "
                    "UI through the default attribute-map printer instead of a function of their data."
                    "\n\nDone when the schema declares both halves of the pair in "
                    "resources/seon/schemas/, and a regression on the canonical database fixture renders "
                    "one entity of this shape through both projections, asserting that the AI projection "
                    "is a string and the HTML projection is hiccup."
                    "\n\nThis issue is generated by seon.issue.detect/entity-map-without-pair: it "
                    "resolves on the run after the pair is declared, and reopens if it is removed.")}
        (contains? namespaces (symbol (namespace schema-key)))
        (assoc :seon.issue/namespaces #{(symbol (namespace schema-key))})))))

(defn entity-map-without-pair
  "Stored entity maps that declare no AI/HTML render pair.

  Excluded: a map whose entities are witnessed as the value of an attribute
  declared `:seon.db/component`. Those render through the owner that holds
  them, so the pair standard does not reach them. The exclusion is the owner's
  own `:seon.db/component` declaration plus one datom witnessing it, never a
  name pattern."
  {:malli/schema [:=> [:cat :seon.db/database-value]
                  [:or [:vector [:map [:seon.schema/key :seon.schema/key]]] :seon.db/error-result]]}
  [database]
  (let [paired (set (db/q '[:find [?key ...] :where
                            [?e :seon.schema/key ?key] [?e :seon.db/attributes true]
                            [?e :seon.render/ai _] [?e :seon.render/html _]]
                          database))
        components (component-values database)
        namespaces (set (db/q '[:find [?name ...] :where [?e :seon.ns/name ?name]] database))]
    (into []
          (comp (remove (comp paired first))
                (keep (partial pair-subject database components namespaces)))
          (sort (db/q '[:find ?key ?e :where
                        [?e :seon.schema/key ?key] [?e :seon.db/attributes true]]
                      database)))))

(defn- shared-form-symbols
  "Symbols of declarations that do not OWN their defining form.

  Several functions sharing one `:seon.fn/form-span` in one file were interned
  by a single form (a `defrecord`'s constructors), so neither a docstring nor a
  `:malli/schema` can be written on them individually. The exclusion is the
  stored span, never a name pattern."
  {:malli/schema [:=> [:cat :seon.db/database-value] [:or [:set :qualified-symbol] :seon.db/error-result]]}
  [database]
  (let [spans (db/q '[:find ?sym ?file ?span :where
                      [?f :seon.fn/sym ?sym] [?f :seon.fn/file ?file] [?f :seon.fn/form-span ?span]]
                    database)]
    (if (and (map? spans) (:seon.error/at spans)
                      (:seon.error/layer spans) (:seon.error/operation spans)) ; debt: seon.db/q and basis-t declare generic errors.

      spans
      (into #{}
            (comp (filter (fn [[_ group]] (> (count group) 1)))
                  (mapcat (fn [[_ group]] (map first group))))
            (group-by (fn [row] [(nth row 1) (nth row 2)]) spans)))))

(defn- carrying
  "The symbols of declarations that carry `attribute` at all.

  One attribute index scan, joined in Clojure by the callers below, so the
  standards differ by WHICH fact is absent and share one candidate query."
  {:malli/schema [:=> [:cat :seon.db/database-value :qualified-keyword] [:or [:set :qualified-symbol] :seon.db/error-result]]}
  [database attribute]
  (let [rows (db/q '[:find [?sym ...] :in $ ?attribute :where
                     [?f :seon.fn/sym ?sym] [?f ?attribute _]]
                   database attribute)]
    (if (and (map? rows) (:seon.error/at rows)
                      (:seon.error/layer rows) (:seon.error/operation rows)) ; debt: seon.db/q and basis-t declare generic errors.
 rows (set rows))))

(def ^:private bodiless-defining-forms
  "Clojure's own var-interning forms that write no body for the author.

  A `deftype`/`defrecord` positional constructor and a `defprotocol` or
  `definterface` method signature are vars nobody gave a body to: there is no
  `defn` to hang `:malli/schema` on and nothing for instrumentation to arm, so
  a missing contract is not a defect there. These are Clojure's names, read
  from the `:seon.fn/defined-by` fact the indexer records, never a roster of
  our own symbols."
  #{'clojure.core/deftype 'clojure.core/defrecord
    'clojure.core/defprotocol 'clojure.core/definterface})

(defn- bodiless-symbols
  "Declarations interned by a form that writes no body."
  {:malli/schema [:=> [:cat :seon.db/database-value] [:or [:set :qualified-symbol] :seon.db/error-result]]}
  [database]
  (let [rows (db/q '[:find [?sym ...] :in $ [?form ...] :where
                     [?f :seon.fn/sym ?sym] [?f :seon.fn/defined-by ?form]]
                   database (vec bodiless-defining-forms))]
    (if (and (map? rows) (:seon.error/at rows)
                      (:seon.error/layer rows) (:seon.error/operation rows)) ; debt: seon.db/q and basis-t declare generic errors.
 rows (set rows))))

(defn- declarations
  "Public source-bearing declarations as sorted `[symbol namespace-name]` rows.

  With no root this is the whole population, test helpers included: an honest
  over-report, not a name-based exclusion. A root joins POSITIVELY on
  `:seon.fn.file/relative-root`, the fact the indexer wrote for the source
  directory it walked the file under, so a declaration under no declared root
  is scoped out rather than assumed to be production."
  {:malli/schema [:=> [:cat :seon.db/database-value [:maybe :seon.fn.file/relative-root]] [:or [:sequential [:tuple :qualified-symbol :symbol]] :seon.db/error-result]]}
  [database root]
  (let [rows (if root
               (db/q '[:find ?sym ?name :in $ ?root :where
                       [?f :seon.fn/sym ?sym] [?f :seon.fn/private? false] [?f :seon.fn/source _]
                       [?f :seon.fn/file ?file] [?file :seon.fn.file/relative-root ?root]
                       [?f :seon.fn/ns ?ns] [?ns :seon.ns/name ?name]]
                     database root)
               (db/q '[:find ?sym ?name :where
                       [?f :seon.fn/sym ?sym] [?f :seon.fn/private? false] [?f :seon.fn/source _]
                       [?f :seon.fn/ns ?ns] [?ns :seon.ns/name ?name]]
                     database))]
    (if (and (map? rows) (:seon.error/at rows)
                      (:seon.error/layer rows) (:seon.error/operation rows)) ; debt: seon.db/q and basis-t declare generic errors.
 rows (sort rows))))

(defn- doc-subject [[sym namespace-name]]
  {:seon.fn/sym sym
   :seon.issue/namespaces #{namespace-name}
   :seon.issue/title (str "Public function " sym " carries no docstring")
   :seon.issue/problem
   (str "The public function " sym " stores source but no :seon.fn/doc, so `doc`, `dir` and the "
        "namespace page answer nothing about what it accepts or promises, and the declaration "
        "teaches an agent reading it nothing."
        "\n\nDone when the definition carries a docstring stating what the function does in terms of "
        "the data it takes and returns, published so that (:seon.fn/doc (seon.db/pull db "
        "[:seon.fn/doc] [:seon.fn/sym '" sym "])) is present."
        "\n\nThis issue is generated by seon.issue.detect/public-without-doc: it resolves on the run "
        "after the docstring is published, and reopens if it is removed.")})

(defn public-without-doc
  "Public source-bearing functions carrying no docstring.

  Excluded: a function that does not OWN its defining form — several functions
  sharing one `:seon.fn/form-span` in one file were interned by a single form
  (a `defrecord`'s constructors), and no docstring can be written on them.

  The one-argument arity is the whole function population, test helpers
  included: an honest over-report, not a name-based exclusion. Given
  `{:seon.fn.file/relative-root \"src\"}` it instead yields the declarations the indexer
  walked under that source root, joining positively on the root the file entity
  carries — a declaration under no declared root is scoped out, never assumed
  to be production."
  {:malli/schema
   [:function
    [:=> [:cat :seon.db/database-value]
     [:or [:vector [:map [:seon.fn/sym :seon.fn/sym]]] :seon.db/error-result]]
    [:=> [:cat :seon.db/database-value
          [:map [:seon.fn.file/relative-root {:optional true} :seon.fn.file/relative-root]]]
     [:or [:vector [:map [:seon.fn/sym :seon.fn/sym]]] :seon.db/error-result]]]}
  ([database] (public-without-doc database {}))
  ([database request]
   (let [subjects (declarations database (:seon.fn.file/relative-root request))
         documented (carrying database :seon.fn/doc)
         shared (shared-form-symbols database)]
     (or (some #(when (and (map? %) (:seon.error/at %)
                      (:seon.error/layer %) (:seon.error/operation %)) ; debt: seon.db/q and basis-t declare generic errors.
 %) [subjects documented shared])
         (into []
               (comp (remove (fn [[sym _]] (or (documented sym) (shared sym)))) (map doc-subject))
               subjects)))))

(defn- contract-subject [[sym namespace-name]]
  {:seon.fn/sym sym
   :seon.issue/namespaces #{namespace-name}
   :seon.issue/title (str "Public function " sym " declares no contract")
   :seon.issue/problem
   (str "The public function " sym " stores source but no :seon.fn/spec, so nothing declares what "
        "it accepts and promises. Instrumentation has no contract to arm, `doc` and `dir` answer "
        "with arglists alone, and a wrong argument surfaces as an arbitrary failure inside the body "
        "instead of a typed refusal naming the function and the offending value."
        "\n\nDone when the definition carries a complete Malli `:malli/schema` on its var metadata — "
        "no :any, :some or [:maybe X] without a genuinely polymorphic boundary — published so that "
        "(:seon.fn/spec (seon.db/pull db [:seon.fn/spec] [:seon.fn/sym '" sym "])) is present."
        "\n\nThis issue is generated by seon.issue.detect/public-without-contract: it resolves on the "
        "run after the contract is published, and reopens if it is removed.")})

(defn public-without-contract
  "Public source-bearing functions declaring no Malli contract.

  Excluded by fact, never by name: a declaration the indexer recorded as a
  macro (`:seon.fn/macro?` — a macro is handed forms, and no macro in the
  population carries `:seon.fn/spec`), a declaration that does not own its
  defining form (several symbols sharing one `:seon.fn/form-span`, which is how
  a `defrecord`'s constructors are interned), and a declaration whose
  `:seon.fn/defined-by` names one of Clojure's bodiless interning forms — a
  `deftype` constructor or a `defprotocol` method signature has no body to
  carry a contract and nothing for instrumentation to arm.

  The one-argument arity is the whole population, test helpers included: an
  honest over-report. Given `{:seon.fn.file/relative-root \"src\"}` it yields the
  declarations the indexer walked under that source root, joining positively on
  the root the file entity carries."
  {:malli/schema
   [:function
    [:=> [:cat :seon.db/database-value]
     [:or [:vector [:map [:seon.fn/sym :seon.fn/sym]]] :seon.db/error-result]]
    [:=> [:cat :seon.db/database-value
          [:map [:seon.fn.file/relative-root {:optional true} :seon.fn.file/relative-root]]]
     [:or [:vector [:map [:seon.fn/sym :seon.fn/sym]]] :seon.db/error-result]]]}
  ([database] (public-without-contract database {}))
  ([database request]
   (let [subjects (declarations database (:seon.fn.file/relative-root request))
         contracted (carrying database :seon.fn/spec)
         macros (carrying database :seon.fn/macro?)
         bodiless (bodiless-symbols database)
         shared (shared-form-symbols database)]
     (or (some #(when (and (map? %) (:seon.error/at %)
                      (:seon.error/layer %) (:seon.error/operation %)) ; debt: seon.db/q and basis-t declare generic errors.
 %)
               [subjects contracted macros bodiless shared])
         (into []
               (comp (remove (fn [[sym _]] (or (contracted sym) (macros sym)
                                               (bodiless sym) (shared sym))))
                     (map contract-subject))
               subjects)))))

(defn- reaching-test-subject [basis-t [sym namespace-name]]
  {:seon.fn/sym sym
   :seon.issue/namespaces #{namespace-name}
   :seon.issue/title (str "No test reaches public function " sym)
   :seon.issue/problem
   (str "No indexed test reaches the public function " sym ". Reach was derived by "
        "seon.fn/tests-reaching — the stored `:seon.fn/calls` walk seon.fn/gate-set uses to select a "
        "commit's gate — over the database value at basis :t " basis-t ", and that walk named no test."
        "\n\nRead this as \"no reach is recorded\", NEVER as \"no test exercises it\": the call graph "
        "can be incomplete when analysis cannot resolve a caller or target. Calls and references both "
        "contribute reach; unresolved file references select that file's tests. "
        "Read the stored reach before writing a new regression."
        "\n\nDone when (seon.fn/tests-reaching (seon.db/db) \"" sym "\") names at least one test — "
        "because a regression now reaches it, or because the edge that was missing is now indexed."
        "\n\nThis issue is generated by seon.issue.detect/public-without-reaching-test: it resolves "
        "on the run after reach appears, and reopens if it disappears.")})

(defn public-without-reaching-test
  "Public source-bearing functions no indexed test reaches.

  Reach is `seon.fn/tests-reaching` — the one stored-edge derivation
  `seon.fn/gate-set` uses to select a commit's gate — asked once per candidate:
  never a name match, never a second reach derivation. A function whose
  references cannot resolve contributes its file's tests conservatively.
  One gate-sets operation shares the declaration relation across candidates.

  The report is honest about its own evidence: the call graph under-reports
  when a target or caller cannot be resolved, so each subject's problem
  text names the basis :t the reach was computed at and says the graph may
  be incomplete. A subject resolves on the run after reach appears —
  whether a regression was written or the missing edge became indexed.

  Excluded by fact: a declaration that does not own its defining form (several
  symbols sharing one `:seon.fn/form-span`).

  The one-argument arity is the whole population, test helpers included. Given
  `{:seon.fn.file/relative-root \"src\"}` it yields the declarations the indexer
  walked under that source root."
  {:malli/schema
   [:function
    [:=> [:cat :seon.db/database-value]
     [:or [:vector [:map [:seon.fn/sym :seon.fn/sym]]] :seon.db/error-result]]
    [:=> [:cat :seon.db/database-value
          [:map [:seon.fn.file/relative-root {:optional true} :seon.fn.file/relative-root]]]
     [:or [:vector [:map [:seon.fn/sym :seon.fn/sym]]] :seon.db/error-result]]]}
  ([database] (public-without-reaching-test database {}))
  ([database request]
   (let [subjects (declarations database (:seon.fn.file/relative-root request))
         shared (shared-form-symbols database)
         basis-t (db/basis-t database)]
     (or (some #(when (or (:seon.db/invalid-read %)
                         (:seon.schema/expected-value %)) %)
               [subjects shared basis-t])
         (let [candidates (remove (fn [[sym _]] (shared sym)) subjects)
               gates (fn/gate-sets database (map first candidates))]
           (if (or (:seon.db/invalid-read gates) (:seon.schema/expected-value gates))
             gates
             (into []
                   (keep (fn [[sym _ :as row]]
                           (when (empty? (get gates sym))
                             (reaching-test-subject basis-t row))))
                   candidates)))))))
