(ns seon.issue.detect
  "Detectors: one database value in, the subjects that fail one standard out.

  A detector is an ordinary read. It returns a vector of subject maps, each
  carrying exactly ONE installed identity attribute and its value — never a
  bare entity id, which a refork would change — plus the prose the generator
  writes once (`:seon.issue/title`, `:seon.issue/problem`) and the namespaces
  responsible for the finding. `seon.issue/generate` turns those subjects into
  issue entities whose identity is the detector plus the subject identity, so
  running a detector twice upserts the same entities."
  (:require [seon.db :as db]))

(defn- declared-keys
  "The attribute keys one entity-map schema declares, from its stored shape."
  [database entity]
  (into #{}
        (keep :seon.schema.map-entry/key-keyword)
        (get-in (db/pull database
                         '[{:seon.schema/shape
                            [{:seon.schema.shape/entries [:seon.schema.map-entry/key-keyword]}]}]
                         entity)
                [:seon.schema/shape :seon.schema.shape/entries])))

(defn- component-values
  "Every entity that is the value of an attribute declared `:seon.db/component`."
  [database]
  (into #{}
        (mapcat (fn [attribute] (map :v (db/datoms database :aevt attribute))))
        (db/q '[:find [?key ...] :where
                [?e :seon.schema/key ?key] [?e :seon.db/component true]]
              database)))

(defn- instances
  "Entities whose whole attribute set lies inside one entity map's declared keys.
  An entity IS its attributes: no kind stamp decides this, and an entity holding
  an attribute the map does not declare is another entity sharing a key."
  [database entity-keys]
  (->> (into #{}
             (mapcat (fn [attribute] (map :e (db/datoms database :aevt attribute))))
             entity-keys)
       (filter (fn [entity]
                 (every? #(contains? entity-keys (:a %)) (db/datoms database :eavt entity))))))

(defn- pair-subject [database components namespaces [schema-key entity]]
  (let [entity-keys (declared-keys database entity)]
    (when-not (some components (instances database entity-keys))
      (cond-> {:seon.schema/key schema-key
               :seon.issue/title (str "Entity map " schema-key " declares no render pair")
               :seon.issue/problem
               (str "The entity map " schema-key " is stored (:seon.db/attributes true) and declares neither "
                    ":seon.render/ai nor :seon.render/html, so its entities reach an agent and the web "
                    "UI through the default attribute-map printer instead of a function of their data."
                    "\n\nDone when the schema declares both halves of the pair in "
                    "resources/seon/schemas/, and a regression on the canonical database fixture renders "
                    "one entity of this shape through both projections, asserting that the AI projection "
                    "is a string and the HTML projection is hiccup."
                    "\n\nThis issue is generated by seon.issue.detect/entity-map-without-pair: it "
                    "resolves on the run after the pair is declared, and reopens if it is removed.")}
        (contains? namespaces (symbol (namespace schema-key)))
        (assoc :seon.issue/namespaces #{(symbol (namespace schema-key))})))))

(defn entity-map-without-pair
  "Stored entity maps that declare no AI/HTML render pair.

  Excluded: a map whose entities are witnessed as the value of an attribute
  declared `:seon.db/component`. Those render through the owner that holds
  them, so the pair standard does not reach them. The exclusion is the owner's
  own `:seon.db/component` declaration plus one datom witnessing it, never a
  name pattern."
  {:malli/schema [:=> [:cat :seon.db/database-value]
                  [:or [:vector [:map [:seon.schema/key :seon.schema/key]]] :seon.error/value]]}
  [database]
  (let [paired (set (db/q '[:find [?key ...] :where
                            [?e :seon.schema/key ?key] [?e :seon.db/attributes true]
                            [?e :seon.render/ai _] [?e :seon.render/html _]]
                          database))
        components (component-values database)
        namespaces (set (db/q '[:find [?name ...] :where [?e :seon.ns/name ?name]] database))]
    (into []
          (comp (remove (comp paired first))
                (keep (partial pair-subject database components namespaces)))
          (sort (db/q '[:find ?key ?e :where
                        [?e :seon.schema/key ?key] [?e :seon.db/attributes true]]
                      database)))))

(defn- doc-subject [[sym namespace-name]]
  {:seon.fn/sym sym
   :seon.issue/namespaces #{namespace-name}
   :seon.issue/title (str "Public function " sym " carries no docstring")
   :seon.issue/problem
   (str "The public function " sym " stores source but no :seon.fn/doc, so `doc`, `dir` and the "
        "namespace page answer nothing about what it accepts or promises, and the declaration "
        "teaches an agent reading it nothing."
        "\n\nDone when the definition carries a docstring stating what the function does in terms of "
        "the data it takes and returns, published so that (:seon.fn/doc (seon.db/pull db "
        "[:seon.fn/doc] [:seon.fn/sym \"" sym "\"])) is present."
        "\n\nThis issue is generated by seon.issue.detect/public-without-doc: it resolves on the run "
        "after the docstring is published, and reopens if it is removed.")})

(defn public-without-doc
  "Public source-bearing functions carrying no docstring.

  Excluded: a function that does not OWN its defining form — several functions
  sharing one `:seon.fn/form-span` in one file were interned by a single form
  (a `defrecord`'s constructors), and no docstring can be written on them."
  {:malli/schema [:=> [:cat :seon.db/database-value]
                  [:or [:vector [:map [:seon.fn/sym :seon.fn/sym]]] :seon.error/value]]}
  [database]
  (let [spans (db/q '[:find ?sym ?file ?span :where
                      [?f :seon.fn/sym ?sym] [?f :seon.fn/file ?file] [?f :seon.fn/form-span ?span]]
                    database)
        shared (into #{}
                     (comp (filter (fn [[_ group]] (> (count group) 1)))
                           (mapcat (fn [[_ group]] (map first group))))
                     (group-by (fn [row] [(nth row 1) (nth row 2)]) spans))]
    (into []
          (comp (remove (comp shared first)) (map doc-subject))
          (sort (db/q '[:find ?sym ?name :where
                        [?f :seon.fn/sym ?sym] [?f :seon.fn/private? false] [?f :seon.fn/source _]
                        [?f :seon.fn/ns ?ns] [?ns :seon.ns/name ?name]
                        (not [?f :seon.fn/doc _])]
                      database)))))
