(ns seon.trading.executor
  "S-expression executor for the reasoning agent.

  Safely evaluates Clojure s-expressions generated by the LLM,
  restricting execution to the DSL primitives only."
  (:require [seon.trading.signals :as primitives]
            [clojure.edn :as edn]))

(def ^:private allowed-symbols
  "Symbols allowed in DSL expressions."
  (into #{'if 'and 'or 'not 'let
          '> '< '>= '<= '= 'not=
          '+ '- '* '/
          'max 'min 'abs
          'true 'false 'nil}
        (keys primitives/primitives)))

(defn- safe-symbol?
  "Check if a symbol is allowed in the DSL."
  [sym]
  (contains? allowed-symbols sym))

(defn- validate-expr
  "Validate that an expression only contains allowed symbols.

  Returns:
    true if valid, throws exception if invalid"
  [expr]
  (cond
    (symbol? expr)
    (when-not (or (safe-symbol? expr)
                  (= (namespace expr) "clojure.core"))
      (throw (ex-info "Disallowed symbol in DSL expression"
                      {:symbol expr})))

    (seq? expr)
    (doseq [item expr]
      (validate-expr item))

    (vector? expr)
    (doseq [item expr]
      (validate-expr item))

    (map? expr)
    (doseq [[k v] expr]
      (validate-expr k)
      (validate-expr v)))
  true)

(defn- build-bindings
  "Build the execution environment bindings."
  [db]
  (into {'db db}
        (map (fn [[k v]]
               [(symbol (name k)) (:fn v)])
             primitives/primitives)))

(defn parse
  "Parse a DSL expression from string.

  Args:
    expr-str - String containing Clojure s-expression

  Returns:
    Parsed expression (data structure)"
  [expr-str]
  (edn/read-string expr-str))

(defn validate
  "Validate a DSL expression.

  Args:
    expr - Parsed expression

  Returns:
    true if valid

  Throws:
    ExceptionInfo if expression contains disallowed symbols"
  [expr]
  (validate-expr expr))

(defn execute
  "Execute a DSL expression against the database.

  The expression has access to all DSL primitives and basic
  Clojure operations (arithmetic, comparisons, conditionals).

  Args:
    db - Database value (frozen T0 environment)
    expr - Parsed DSL expression

  Returns:
    Result of the expression

  Example:
    (execute db '(if (< (iv-rank db \"AAPL\") 0.1)
                   :buy-straddle
                   :pass))"
  [db expr]
  (validate expr)
  (let [bindings (build-bindings db)
        eval-fn (fn [e]
                  (cond
                    (symbol? e) (get bindings e e)
                    (seq? e) (let [[f & args] e
                                   resolved-f (get bindings f f)
                                   resolved-args (map #(execute db %) args)]
                               (apply resolved-f resolved-args))
                    :else e))]
    (eval-fn expr)))

(defn execute-trace
  "Execute a reasoning trace (sequence of expressions).

  Returns results for each step, enabling analysis of the
  agent's reasoning process.

  Args:
    db - Database value
    trace - Sequence of expressions

  Returns:
    Sequence of {:expr :result :error} maps"
  [db trace]
  (mapv (fn [expr]
          (try
            {:expr expr
             :result (execute db expr)
             :error nil}
            (catch Exception e
              {:expr expr
               :result nil
               :error (.getMessage e)})))
        trace))

(defn compile-rule
  "Compile a DSL expression to a callable function.

  The returned function takes a database value and returns
  the result of the expression.

  Args:
    expr - Parsed DSL expression

  Returns:
    Function (fn [db] -> result)"
  [expr]
  (validate expr)
  (fn [db]
    (execute db expr)))

(defn rule->str
  "Convert a compiled rule back to string form.

  Args:
    expr - DSL expression

  Returns:
    String representation"
  [expr]
  (pr-str expr))

(comment
  ;; Example usage:

  ;; Parse and validate
  (def expr (parse "(if (< (iv-rank db \"AAPL\") 0.1) :buy :hold)"))
  (validate expr)

  ;; Execute against a database
  ;; (execute my-db expr)

  ;; Compile to reusable function
  (def my-rule (compile-rule expr))
  ;; (my-rule my-db)
  )
