(require '[sci.core :as sci] '[sci.interrupt])
(ns throwaway)
(defn victim [] :ORIGINAL)
(def ^:dynamic *dv* :orig)
(in-ns 'user)
(require '[sci.core :as sci] '[sci.interrupt])
(def ctx (sci/init {:namespaces {'clojure.core sci.interrupt/clojure-core}}))
(sci/add-namespace! ctx 'throwaway (ns-interns 'throwaway))
(sci/add-namespace! ctx 'ctxholder {'get-ctx (sci/copy-var* #'clojure.core/identity (sci/create-ns 'ctxholder))})
(defn p [l code] (println l (try (pr-str (sci/eval-string* ctx code)) (catch Throwable t (str "THREW: " (ex-message t))))))
(p "resolve var obj:" "#'throwaway/victim")
(p "class of var obj:" "(str (type #'throwaway/victim))")
(p "call through var:" "(#'throwaway/victim)")
(p "alter-var-root:" "(alter-var-root #'throwaway/victim (constantly (fn [] :PWNED)))")
(p "with-redefs:" "(with-redefs [throwaway/victim (fn [] :REDEF)] (throwaway/victim))")
(p "var-set:" "(var-set #'throwaway/victim (fn [] :SET))")
(p "binding host dynvar:" "(binding [throwaway/*dv* :BOUND] throwaway/*dv*)")
(p "intern:" "(intern 'throwaway 'victim (fn [] :INTERNED))")
(p "alter-meta!:" "(alter-meta! #'throwaway/victim assoc :pwned true)")
(p "push-thread-bindings:" "(push-thread-bindings {#'throwaway/*dv* :PUSHED})")
(p "ns-unmap on host ns:" "(ns-unmap 'throwaway 'victim)")
(println "HOST victim after all attempts:" (throwaway/victim))
(println "HOST *dv* after:" throwaway/*dv*)
(println "HOST meta pwned?:" (:pwned (meta #'throwaway/victim)))
;; the ctx env atom: reachable if any reachable value contains the ctx
(println "--- ctx env atom reachability ---")
(sci/add-namespace! ctx 'holder {'the-ctx (sci/new-var 'the-ctx ctx {:ns (sci/create-ns 'holder)})})
(p "env atom from ctx map:" "(str (type (:env holder/the-ctx)))")
(p "swap env to redefine:" "(do (swap! (:env holder/the-ctx) assoc-in [:namespaces 'throwaway 'victim] (sci/new-var 'victim (fn [] :ENV-PWNED) {})) :swapped)")
(p "after env swap:" "(throwaway/victim)")
