(require '[datahike.api :as d])
(def cfg {:store {:backend :memory :id (random-uuid)} :keep-history? true :schema-flexibility :write})
(d/delete-database cfg) (d/create-database cfg)
(def conn (d/connect cfg))
(d/transact conn [{:db/ident :m/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
                  {:db/ident :m/text :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
                  {:db/ident :m/read? :db/valueType :db.type/boolean :db/cardinality :db.cardinality/one}])
(d/transact conn (vec (for [i (range 500)] {:m/id (str "m" i) :m/text (str "t" i) :m/read? (even? i)})))
(def db @conn)
(def touched (atom []))
(def rec (d/filter db (fn [_db datom] (swap! touched conj [(:e datom) (:a datom) (:tx datom)]) true)))
(reset! touched [])
(def result (d/q '[:find ?id ?t :where [?e :m/read? true] [?e :m/id ?id] [?e :m/text ?t]] rec))
(println :result-count (count result))
(println :touched-datoms (count @touched))
(println :distinct-entities (count (distinct (map first @touched))))
(println :distinct-attrs (distinct (map second @touched)))
(println :max-tx-touched (apply max (map #(nth % 2) @touched)))
(reset! touched [])
(def p (d/pull rec '[*] [:m/id "m3"]))
(println :pull p)
(println :pull-touched (count @touched))
;; do the touched datoms let us answer "did anything this read change since t"?
(println :db-max-tx (:max-tx db))
