;; Exact successful JVM forms, executed separately with explicit default custody.
;; The first sends ONE message through the canonical fixture. Do not load this
;; file wholesale or replay its send to inspect historical evidence.

(let [c (seon.operator/connection "default") d (seon.db/db c) instance (get @seon.operator.runtime/running-instances "default") h (:seon.turn.loop/cluster instance) disabled (seon.db/q '[:find ?v . :where [?a :seon.agent/id "juniper"] [?a :seon.agent/settings ?s] [?s :seon.config.ai/no-provider ?v]] d)] (assert (= 94566 (.pid (java.lang.ProcessHandle/current)))) (assert (true? disabled)) (prn {:probe/phase :pre-send :probe/pid (.pid (java.lang.ProcessHandle/current)) :probe/basis (seon.db/basis-t d) :probe/no-provider disabled}) (seon.schema/call-with-projection-state (:seon.sci.eval/projection-state h) (fn [] ((requiring-resolve 'seon.context-blocks-fixture/submit!) h (:seon.agent/routing instance) "(my.message/send {:my.message/to \"juniper\" :my.message/content \"Message wake live proof 2026-09-17 db4a5526d\"})"))) (let [d (seon.db/db c) m (seon.db/q '[:find ?id . :where [?m :seon.message/content "Message wake live proof 2026-09-17 db4a5526d"] [?m :seon.message/id ?id]] d) eid (:db/id (seon.db/pull d [:db/id] [:seon.message/id m]))] (prn {:probe/phase :before :probe/pid (.pid (java.lang.ProcessHandle/current)) :probe/basis (seon.db/basis-t d) :probe/message m :probe/listened (contains? (seon.cluster.wake/wake-attributes d) :seon.message/to) :probe/route (seon.db/q '[:find ?m ?a ?t :in $ ?m :where [?m :seon.message/to ?a ?t]] d eid) :probe/claims (seon.db/q '[:find ?id ?t :in $ ?m :where [?r :seon.turn/handled ?m ?t] [?r :seon.turn/id ?id]] d eid) :probe/answering-t (seon.turn/latest-answering-turn-t d "juniper") :probe/unanswered (filterv #(= m (:seon.message/id %)) (seon.turn/unanswered-wakes d "juniper" {})) :probe/all (filterv #(= m (:seon.message/id %)) (seon.turn/unanswered-wakes d "juniper" {:seon.turn.work/answered? :any}))})))

(let [c (seon.operator/connection "default") d (seon.db/db c) m "3168e0a55d3d" eid (:db/id (seon.db/pull d [:db/id] [:seon.message/id m]))] (assert (= 94566 (.pid (java.lang.ProcessHandle/current)))) (prn {:probe/phase :after :probe/pid (.pid (java.lang.ProcessHandle/current)) :probe/basis (seon.db/basis-t d) :probe/message m :probe/no-provider (seon.db/q '[:find ?v . :where [?a :seon.agent/id "juniper"] [?a :seon.agent/settings ?s] [?s :seon.config.ai/no-provider ?v]] d) :probe/route (seon.db/q '[:find ?m ?a ?t :in $ ?m :where [?m :seon.message/to ?a ?t]] d eid) :probe/claims (seon.db/q '[:find ?id ?opened ?replied ?closed ?claimed :in $ ?m :where [?r :seon.turn/handled ?m ?claimed] [?r :seon.turn/id ?id ?opened] [?r :seon.turn/reply-size _ ?replied] [?r :seon.turn/closed-tx ?closed]] d eid) :probe/open (seon.turn/open-for-agent d [:seon.agent/id "juniper"]) :probe/answering-t (seon.turn/latest-answering-turn-t d "juniper") :probe/unanswered (filterv #(= m (:seon.message/id %)) (seon.turn/unanswered-wakes d "juniper" {})) :probe/all (filterv #(= m (:seon.message/id %)) (seon.turn/unanswered-wakes d "juniper" {:seon.turn.work/answered? :any}))}))

(let [d (seon.db/db (seon.operator/connection "default")) old (seon.db/as-of d 536871184) turn "3ded5c0bc8a4"] (prn {:probe/pid (.pid (java.lang.ProcessHandle/current)) :probe/basis (seon.db/basis-t d) :probe/open-at-536871184 (seon.turn/open-for-agent old [:seon.agent/id "juniper"]) :probe/claims-at-opening (seon.db/q '[:find ?r :where [?r :seon.turn/handled ?m] [?m :seon.message/id "3168e0a55d3d"]] old) :probe/attempts (seon.db/q '[:find ?a :in $ ?id :where [?r :seon.turn/id ?id] [?r :seon.turn/attempts ?a]] d turn) :probe/answered-by-t (<= 536871180 (seon.turn/latest-answering-turn-t d "juniper")) :probe/error-signatures (seon.db/q '[:find (count ?s) . :where [?e :seon.error/signature ?s]] d)}))
